{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "182ae022-3663-4cdb-b0c2-de3e7c24cdbc",
   "metadata": {},
   "source": [
    "## 13 Feb Assignment"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7096af14-38f3-41f7-819c-d623c0a453b9",
   "metadata": {},
   "source": [
    "### Q1.Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9ba264e1-b6fc-4489-8991-a3836124a834",
   "metadata": {},
   "source": [
    "#### Ans: In Python, the Exception class serves as the base class for all built-in and custom exceptions. When creating a custom exception, it is important to derive it from the Exception class for several reasons:\n",
    "\n",
    "#### Inheritance: By inheriting from the Exception class, custom exception inherits all the features and behaviors of the base class. This includes the ability to capture and propagate exceptions, handle them in a uniform manner, and utilize the existing exception handling mechanisms provided by the Python language.\n",
    "\n",
    "#### Compatibility: Deriving from Exception ensures that custom exception is compatible with the exception handling infrastructure in Python. This allows you to catch and handle the custom exception using the same try-except statements and other exception handling constructs that are used for built-in exceptions.\n",
    "\n",
    "#### Consistency: Python follows the principle of consistent and uniform exception handling. By extending the Exception class, it adhere to this principle and make custom exception fit seamlessly into the existing exception hierarchy.\n",
    "\n",
    "#### Customization: The Exception class provides various methods and attributes that can be override or customize in custom exception. For example, you can define a custom error message, add additional properties or methods specific to your exception, or implement specialized behavior. By inheriting from Exception, you gain the flexibility to tailor your exception to suit your specific needs.\n",
    "\n",
    "#### Interoperability: Deriving from Exception enables your custom exception to be used alongside other built-in exceptions in various scenarios. This includes scenarios where exceptions are propagated across different parts of the code, caught and handled by different modules or libraries, or when interacting with other Python code that expects exceptions to adhere to the standard Exception interface.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "81da1602-9c47-492c-b125-145d354933bd",
   "metadata": {},
   "source": [
    "### Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ae3511b6-e558-4f66-b8f9-320974f0efaf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hierarchy for Built-in exceptions is : \n",
      " BaseException\n",
      "--- Exception\n",
      "------ TypeError\n",
      "--------- FloatOperation\n",
      "--------- MultipartConversionError\n",
      "------ StopAsyncIteration\n",
      "------ StopIteration\n",
      "------ ImportError\n",
      "--------- ModuleNotFoundError\n",
      "--------- ZipImportError\n",
      "------ OSError\n",
      "--------- ConnectionError\n",
      "------------ BrokenPipeError\n",
      "------------ ConnectionAbortedError\n",
      "------------ ConnectionRefusedError\n",
      "------------ ConnectionResetError\n",
      "--------------- RemoteDisconnected\n",
      "--------- BlockingIOError\n",
      "--------- ChildProcessError\n",
      "--------- FileExistsError\n",
      "--------- FileNotFoundError\n",
      "--------- IsADirectoryError\n",
      "--------- NotADirectoryError\n",
      "--------- InterruptedError\n",
      "------------ InterruptedSystemCall\n",
      "--------- PermissionError\n",
      "--------- ProcessLookupError\n",
      "--------- TimeoutError\n",
      "--------- UnsupportedOperation\n",
      "--------- itimer_error\n",
      "--------- herror\n",
      "--------- gaierror\n",
      "--------- SSLError\n",
      "------------ SSLCertVerificationError\n",
      "------------ SSLZeroReturnError\n",
      "------------ SSLWantWriteError\n",
      "------------ SSLWantReadError\n",
      "------------ SSLSyscallError\n",
      "------------ SSLEOFError\n",
      "--------- Error\n",
      "------------ SameFileError\n",
      "--------- SpecialFileError\n",
      "--------- ExecError\n",
      "--------- ReadError\n",
      "--------- URLError\n",
      "------------ HTTPError\n",
      "------------ ContentTooShortError\n",
      "--------- BadGzipFile\n",
      "------ EOFError\n",
      "--------- IncompleteReadError\n",
      "------ RuntimeError\n",
      "--------- RecursionError\n",
      "--------- NotImplementedError\n",
      "------------ ZMQVersionError\n",
      "------------ StdinNotImplementedError\n",
      "--------- _DeadlockError\n",
      "--------- BrokenBarrierError\n",
      "--------- BrokenExecutor\n",
      "------------ BrokenThreadPool\n",
      "--------- SendfileNotAvailableError\n",
      "--------- ExtractionError\n",
      "--------- VariableError\n",
      "------ NameError\n",
      "--------- UnboundLocalError\n",
      "------ AttributeError\n",
      "--------- FrozenInstanceError\n",
      "------ SyntaxError\n",
      "--------- IndentationError\n",
      "------------ TabError\n",
      "------ LookupError\n",
      "--------- IndexError\n",
      "--------- KeyError\n",
      "------------ NoSuchKernel\n",
      "------------ UnknownBackend\n",
      "--------- CodecRegistryError\n",
      "------ ValueError\n",
      "--------- UnicodeError\n",
      "------------ UnicodeEncodeError\n",
      "------------ UnicodeDecodeError\n",
      "------------ UnicodeTranslateError\n",
      "--------- UnsupportedOperation\n",
      "--------- JSONDecodeError\n",
      "--------- SSLCertVerificationError\n",
      "--------- Error\n",
      "--------- UnsupportedDigestmodError\n",
      "--------- IllegalMonthError\n",
      "--------- IllegalWeekdayError\n",
      "--------- ParserError\n",
      "--------- ClassNotFound\n",
      "--------- ClipboardEmpty\n",
      "--------- MessageDefect\n",
      "------------ NoBoundaryInMultipartDefect\n",
      "------------ StartBoundaryNotFoundDefect\n",
      "------------ CloseBoundaryNotFoundDefect\n",
      "------------ FirstHeaderLineIsContinuationDefect\n",
      "------------ MisplacedEnvelopeHeaderDefect\n",
      "------------ MissingHeaderBodySeparatorDefect\n",
      "------------ MultipartInvariantViolationDefect\n",
      "------------ InvalidMultipartContentTransferEncodingDefect\n",
      "------------ UndecodableBytesDefect\n",
      "------------ InvalidBase64PaddingDefect\n",
      "------------ InvalidBase64CharactersDefect\n",
      "------------ InvalidBase64LengthDefect\n",
      "------------ HeaderDefect\n",
      "--------------- InvalidHeaderDefect\n",
      "--------------- HeaderMissingRequiredValue\n",
      "--------------- NonPrintableDefect\n",
      "--------------- ObsoleteHeaderDefect\n",
      "--------------- NonASCIILocalPartDefect\n",
      "--------------- InvalidDateDefect\n",
      "--------- MacroToEdit\n",
      "--------- InvalidFileException\n",
      "--------- UnequalIterablesError\n",
      "--------- InvalidVersion\n",
      "--------- _InvalidELFFileHeader\n",
      "--------- InvalidWheelFilename\n",
      "--------- InvalidSdistFilename\n",
      "--------- InvalidSpecifier\n",
      "--------- InvalidMarker\n",
      "--------- UndefinedComparison\n",
      "--------- UndefinedEnvironmentName\n",
      "--------- InvalidRequirement\n",
      "------------ RequirementParseError\n",
      "--------- InvalidVersion\n",
      "------ AssertionError\n",
      "------ ArithmeticError\n",
      "--------- FloatingPointError\n",
      "--------- OverflowError\n",
      "--------- ZeroDivisionError\n",
      "------------ DivisionByZero\n",
      "------------ DivisionUndefined\n",
      "--------- DecimalException\n",
      "------------ Clamped\n",
      "------------ Rounded\n",
      "--------------- Underflow\n",
      "--------------- Overflow\n",
      "------------ Inexact\n",
      "--------------- Underflow\n",
      "--------------- Overflow\n",
      "------------ Subnormal\n",
      "--------------- Underflow\n",
      "------------ DivisionByZero\n",
      "------------ FloatOperation\n",
      "------------ InvalidOperation\n",
      "--------------- ConversionSyntax\n",
      "--------------- DivisionImpossible\n",
      "--------------- DivisionUndefined\n",
      "--------------- InvalidContext\n",
      "------ SystemError\n",
      "--------- CodecRegistryError\n",
      "------ ReferenceError\n",
      "------ MemoryError\n",
      "------ BufferError\n",
      "------ Warning\n",
      "--------- UserWarning\n",
      "------------ GetPassWarning\n",
      "------------ FormatterWarning\n",
      "--------- EncodingWarning\n",
      "--------- DeprecationWarning\n",
      "------------ ProvisionalWarning\n",
      "--------- PendingDeprecationWarning\n",
      "--------- SyntaxWarning\n",
      "--------- RuntimeWarning\n",
      "------------ ProactorSelectorThreadWarning\n",
      "------------ UnknownTimezoneWarning\n",
      "------------ PEP440Warning\n",
      "--------- FutureWarning\n",
      "------------ ProvisionalCompleterWarning\n",
      "--------- ImportWarning\n",
      "--------- UnicodeWarning\n",
      "--------- BytesWarning\n",
      "--------- ResourceWarning\n",
      "--------- DeprecatedTzFormatWarning\n",
      "--------- PkgResourcesDeprecationWarning\n",
      "------ _OptionError\n",
      "------ _Error\n",
      "------ error\n",
      "------ Verbose\n",
      "------ Error\n",
      "------ SubprocessError\n",
      "--------- CalledProcessError\n",
      "--------- TimeoutExpired\n",
      "------ TokenError\n",
      "------ StopTokenizing\n",
      "------ ClassFoundException\n",
      "------ EndOfBlock\n",
      "------ TraitError\n",
      "------ Error\n",
      "------ Error\n",
      "--------- CancelledError\n",
      "--------- TimeoutError\n",
      "--------- InvalidStateError\n",
      "------ _GiveupOnSendfile\n",
      "------ error\n",
      "------ Incomplete\n",
      "------ TimeoutError\n",
      "------ InvalidStateError\n",
      "------ LimitOverrunError\n",
      "------ QueueEmpty\n",
      "------ QueueFull\n",
      "------ Empty\n",
      "------ Full\n",
      "------ ArgumentError\n",
      "------ ZMQBaseError\n",
      "--------- ZMQError\n",
      "------------ ContextTerminated\n",
      "------------ Again\n",
      "------------ InterruptedSystemCall\n",
      "--------- ZMQBindError\n",
      "--------- NotDone\n",
      "------ PickleError\n",
      "--------- PicklingError\n",
      "--------- UnpicklingError\n",
      "------ _Stop\n",
      "------ ArgumentError\n",
      "------ ArgumentTypeError\n",
      "------ ConfigError\n",
      "--------- ConfigLoaderError\n",
      "------------ ArgumentError\n",
      "--------- ConfigFileNotFound\n",
      "------ ConfigurableError\n",
      "--------- MultipleInstanceError\n",
      "------ ApplicationError\n",
      "------ error\n",
      "------ TimeoutError\n",
      "------ error\n",
      "------ ReturnValueIgnoredError\n",
      "------ KeyReuseError\n",
      "------ UnknownKeyError\n",
      "------ LeakedCallbackError\n",
      "------ BadYieldError\n",
      "------ ReturnValueIgnoredError\n",
      "------ Return\n",
      "------ InvalidPortNumber\n",
      "------ error\n",
      "------ LZMAError\n",
      "------ RegistryError\n",
      "------ _GiveupOnFastCopy\n",
      "------ Error\n",
      "--------- NoSectionError\n",
      "--------- DuplicateSectionError\n",
      "--------- DuplicateOptionError\n",
      "--------- NoOptionError\n",
      "--------- InterpolationError\n",
      "------------ InterpolationMissingOptionError\n",
      "------------ InterpolationSyntaxError\n",
      "------------ InterpolationDepthError\n",
      "--------- ParsingError\n",
      "------------ MissingSectionHeaderError\n",
      "------ NoIPAddresses\n",
      "------ BadZipFile\n",
      "------ LargeZipFile\n",
      "------ BadEntryPoint\n",
      "------ NoSuchEntryPoint\n",
      "------ DuplicateKernelError\n",
      "------ ErrorDuringImport\n",
      "------ NotOneValueFound\n",
      "------ CannotEval\n",
      "------ OptionError\n",
      "------ BdbQuit\n",
      "------ Restart\n",
      "------ ExceptionPexpect\n",
      "--------- EOF\n",
      "--------- TIMEOUT\n",
      "------ PtyProcessError\n",
      "------ FindCmdError\n",
      "------ HomeDirError\n",
      "------ ProfileDirError\n",
      "------ IPythonCoreError\n",
      "--------- TryNext\n",
      "--------- UsageError\n",
      "--------- StdinNotImplementedError\n",
      "------ InputRejected\n",
      "------ GetoptError\n",
      "------ ErrorToken\n",
      "------ PrefilterError\n",
      "------ AliasError\n",
      "--------- InvalidAliasError\n",
      "------ Error\n",
      "--------- InterfaceError\n",
      "--------- DatabaseError\n",
      "------------ InternalError\n",
      "------------ OperationalError\n",
      "------------ ProgrammingError\n",
      "------------ IntegrityError\n",
      "------------ DataError\n",
      "------------ NotSupportedError\n",
      "------ Warning\n",
      "------ SpaceInInput\n",
      "------ DOMException\n",
      "--------- IndexSizeErr\n",
      "--------- DomstringSizeErr\n",
      "--------- HierarchyRequestErr\n",
      "--------- WrongDocumentErr\n",
      "--------- InvalidCharacterErr\n",
      "--------- NoDataAllowedErr\n",
      "--------- NoModificationAllowedErr\n",
      "--------- NotFoundErr\n",
      "--------- NotSupportedErr\n",
      "--------- InuseAttributeErr\n",
      "--------- InvalidStateErr\n",
      "--------- SyntaxErr\n",
      "--------- InvalidModificationErr\n",
      "--------- NamespaceErr\n",
      "--------- InvalidAccessErr\n",
      "--------- ValidationErr\n",
      "------ ValidationError\n",
      "------ EditReadOnlyBuffer\n",
      "------ _Retry\n",
      "------ InvalidLayoutError\n",
      "------ HeightIsUnknownError\n",
      "------ ParserSyntaxError\n",
      "------ InternalParseError\n",
      "------ _PositionUpdatingFinished\n",
      "------ SimpleGetItemNotFound\n",
      "------ UncaughtAttributeError\n",
      "------ HasNoContext\n",
      "------ ParamIssue\n",
      "------ _JediError\n",
      "--------- InternalError\n",
      "--------- WrongVersion\n",
      "--------- RefactoringError\n",
      "------ OnErrorLeaf\n",
      "------ InvalidPythonEnvironment\n",
      "------ MessageError\n",
      "--------- MessageParseError\n",
      "------------ HeaderParseError\n",
      "------------ BoundaryError\n",
      "--------- MultipartConversionError\n",
      "--------- CharsetError\n",
      "------ Error\n",
      "------ HTTPException\n",
      "--------- NotConnected\n",
      "--------- InvalidURL\n",
      "--------- UnknownProtocol\n",
      "--------- UnknownTransferEncoding\n",
      "--------- UnimplementedFileMode\n",
      "--------- IncompleteRead\n",
      "--------- ImproperConnectionState\n",
      "------------ CannotSendRequest\n",
      "------------ CannotSendHeader\n",
      "------------ ResponseNotReady\n",
      "--------- BadStatusLine\n",
      "------------ RemoteDisconnected\n",
      "--------- LineTooLong\n",
      "------ InteractivelyDefined\n",
      "------ KillEmbedded\n",
      "------ Error\n",
      "--------- NoSuchProcess\n",
      "------------ ZombieProcess\n",
      "--------- AccessDenied\n",
      "--------- TimeoutExpired\n",
      "------ _Ipv6UnsupportedError\n",
      "------ QueueEmpty\n",
      "------ QueueFull\n",
      "------ DebuggerInitializationError\n",
      "------ ExpatError\n",
      "------ Error\n",
      "--------- ProtocolError\n",
      "--------- ResponseError\n",
      "--------- Fault\n",
      "------ ParseBaseException\n",
      "--------- ParseException\n",
      "--------- ParseFatalException\n",
      "------------ ParseSyntaxException\n",
      "------ RecursiveGrammarException\n",
      "------ ResolutionError\n",
      "--------- VersionConflict\n",
      "------------ ContextualVersionConflict\n",
      "--------- DistributionNotFound\n",
      "--------- UnknownExtra\n",
      "------ _Error\n",
      "------ UnableToResolveVariableException\n",
      "------ InvalidTypeInArgsException\n",
      "--- GeneratorExit\n",
      "--- SystemExit\n",
      "--- KeyboardInterrupt\n",
      "--- CancelledError\n",
      "--- AbortThread\n"
     ]
    }
   ],
   "source": [
    "# Code\n",
    "\n",
    "# import inspect module\n",
    "import inspect\n",
    "\n",
    "# our treeClass function\n",
    "def treeClass(cls, ind = 0):\n",
    "\t\n",
    "\t# print name of the class\n",
    "\tprint ('-' * ind, cls.__name__)\n",
    "\t\n",
    "\t# iterating through subclasses\n",
    "\tfor i in cls.__subclasses__():\n",
    "\t\ttreeClass(i, ind + 3)\n",
    "\n",
    "print(\"Hierarchy for Built-in exceptions is : \")\n",
    "\n",
    "# inspect.getmro() Return a tuple\n",
    "# of class cls’s base classes.\n",
    "\n",
    "# building a tree hierarchy\n",
    "inspect.getclasstree(inspect.getmro(BaseException))\n",
    "\n",
    "# function call\n",
    "treeClass(BaseException)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0dbb2339-71ab-4ae6-8e6b-9bd992daa078",
   "metadata": {},
   "source": [
    "### Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "619df90b-c1a2-4631-9c2c-3a98a6637813",
   "metadata": {},
   "source": [
    "#### Ans: \n",
    "\n",
    "#### The ArithmeticError class in Python is a base class for exceptions that occur during arithmetic operations. It encompasses several specific error classes that are related to arithmetic calculations. Two commonly encountered errors defined within the ArithmeticError class are ZeroDivisionError and OverflowError.\n",
    "\n",
    "#### 1. ZeroDivisionError: This error occurs when you attempt to divide a number by zero."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "13c3081a-6c78-437e-a5a3-4c93e2d4aeee",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero!\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero!\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dfe455dd-0943-4917-8f8a-292b143cba51",
   "metadata": {},
   "source": [
    "#### In the example above, an attempt is made to divide the number 10 by zero. Since division by zero is undefined, a ZeroDivisionError is raised. The try-except block catches the exception, allowing you to handle it gracefully and display an appropriate error message."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e7086c22-4e16-44a3-ae3b-fa1a6eaa98b9",
   "metadata": {},
   "source": [
    "#### 2. OverflowError: This error occurs when a calculation exceeds the maximum limit of the data type."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "fabd0e91-f5f9-451b-ab1d-71e14045d2b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "try:\n",
    "    result = sys.maxsize ** 2\n",
    "except OverflowError:\n",
    "    print(\"Error: Calculation exceeds maximum limit!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bf6ea144-dd43-4de5-84fd-a963307dbdac",
   "metadata": {},
   "source": [
    "#### In the example above, sys.maxsize represents the maximum value that an integer can hold in Python. The calculation sys.maxsize ** 2 attempts to square this maximum value, which results in a number that exceeds the maximum limit for the integer data type. As a result, an OverflowError is raised, indicating that the calculation has overflowed."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a43314b1-d0d1-4e5c-b8dc-20d254cd0a04",
   "metadata": {},
   "source": [
    "### Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ef360b15-8ebf-4c0a-a4a9-e01da3b63afe",
   "metadata": {},
   "source": [
    "#### Ans: The LookupError class in Python is a base class for exceptions that occur when a lookup or indexing operation fails. It serves as the parent class for specific lookup-related error classes, such as KeyError and IndexError.\n",
    "\n",
    "#### 1. KeyError: This error occurs when you try to access a dictionary using a key that does not exist in the dictionary."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "85bdafef-e105-437d-8ad1-50d6ee9587ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Key does not exist!\n"
     ]
    }
   ],
   "source": [
    "#Code\n",
    "my_dict = {'name': 'John', 'age': 25}\n",
    "\n",
    "try:\n",
    "    value = my_dict['address']\n",
    "except KeyError:\n",
    "    print(\"Error: Key does not exist!\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "309fa7c6-d4c4-4cf8-bb7b-3da09e366d35",
   "metadata": {},
   "source": [
    "#### 2. IndexError: This error occurs when you try to access a sequence (such as a list or a string) using an index that is out of range."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "686c80c6-94b2-4fe1-a9a8-53afb2ab23d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Index out of range!\n"
     ]
    }
   ],
   "source": [
    "#Code\n",
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[5]\n",
    "except IndexError:\n",
    "    print(\"Error: Index out of range!\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "77a2ad31-679b-40d9-bd5b-98552179edbe",
   "metadata": {},
   "source": [
    "### Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41b5226e-b962-4c68-8c9b-48919b50fd3f",
   "metadata": {},
   "source": [
    "#### Ans: In Python, ImportError is an exception that occurs when an import statement fails to import a module. It is a built-in exception that is raised when there are issues related to module imports.\n",
    "\n",
    "#### The ImportError exception can be raised in various scenarios, including:\n",
    "\n",
    "1. When the specified module does not exist: If the module you are trying to import does not exist or cannot be found, an ImportError is raised. \n",
    "\n",
    "2. When there are circular imports: Circular imports happen when two or more modules depend on each other, creating a circular dependency. In such cases, Python raises an ImportError to prevent infinite recursion.\n",
    "\n",
    "3. When there are issues with the module's code: This can occur due to syntax errors, runtime errors, or missing dependencies within the module.\n",
    "\n",
    "4. When there are issues with submodules or package imports: If the module you are importing is a package or contains submodules, an ImportError can be raised if there are problems with importing the submodules or resolving the package structure.\n",
    "\n",
    "#### On the other hand, ModuleNotFoundError is a subclass of ImportError that specifically indicates that the module being imported cannot be found. It was introduced in Python 3.6 as a more specific exception to indicate module import failures.\n",
    "\n",
    "#### When an ImportError occurs, including a ModuleNotFoundError, it typically indicates a problem with the module import statement. This can be due to missing or incorrect module names, issues with the module's location or installation, or problems with the module's code itself."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5dee02bc-2867-4e10-ab91-3a6fb3f90739",
   "metadata": {},
   "source": [
    "### Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d2540f6f-d6ad-4391-a0f1-c955bc7358f1",
   "metadata": {},
   "source": [
    "#### Ans: \n",
    "\n",
    "1. Be specific in exception handling: Catch specific exceptions whenever possible instead of using a broad Exception catch-all. This allows you to handle different exceptions differently and provides better error diagnosis and debugging.\n",
    "\n",
    "2. Use multiple except blocks: If you need to handle different exceptions in different ways, use multiple except blocks. This allows you to provide specific error handling logic for each type of exception.\n",
    "\n",
    "3. Handle exceptions gracefully: Instead of letting exceptions propagate and crash the program, handle them gracefully using try-except blocks. This helps prevent program termination and allows for controlled error handling.\n",
    "\n",
    "4. Avoid bare except statements: Avoid using bare except statements without specifying the exception type. This can lead to hiding and ignoring errors that you should be aware of. Always be explicit in catching the expected exceptions.\n",
    "\n",
    "5. Use finally block for cleanup: When necessary, use a finally block to ensure that certain cleanup actions, such as closing files or releasing resources, are performed regardless of whether an exception occurred or not.\n",
    "\n",
    "6. Reraise exceptions when necessary: If you catch an exception but cannot handle it adequately, consider reraising the exception using raise without any arguments. This allows the exception to propagate up the call stack, providing higher-level code the opportunity to handle it appropriately.\n",
    "\n",
    "7. Provide helpful error messages: When catching an exception, provide meaningful and descriptive error messages that help in identifying the cause of the error. This aids in debugging and troubleshooting.\n",
    "\n",
    "8. Avoid unnecessary try-except blocks: Only use try-except blocks where exceptions are likely to occur. Placing every line of code within a try-except block can hinder performance and make code harder to read and maintain.\n",
    "\n",
    "9. Use context managers for resource management: When working with resources like files or database connections, use context managers (with statement) to ensure proper resource cleanup and handling of exceptions.\n",
    "\n",
    "10. Log exceptions: Consider logging exceptions using a logging framework. This helps in monitoring and debugging applications in production environments.\n",
    "\n",
    "#### Remember that exception handling should strike a balance between error reporting and program flow control. Aim to catch and handle exceptions at the appropriate level of your code, providing informative error messages and ensuring that the program continues to function correctly in the face of exceptional conditions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64dda5c1-8775-4429-981c-b4f116e2e905",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
